# --- Model Classes & Descriptions ---
classes = [
    "The Scribbling Stage",
    "The Preschematic Stage",
    "The Schematic Stage",
    "The Gang Age",
    "The Stage of Reasoning",
    "Adolescent Art"
]

stages_info = {
    "🖍️ The Scribbling Stage (2-4 years old)": "Random lines and shapes – early motor development and expression.",
    "🌈 The Preschematic Stage (4-7 years old)": "First attempts at symbols – recognizable forms appear.",
    "🏠 The Schematic Stage (7-9 years old)": "Consistent symbols like houses, trees, and people emerge.",
    "👫 The Gang Age (9-11 years old)": "Peer influence and better spatial understanding.",
    "🧠 The Stage of Reasoning (11-13 years old)": "Realism increases, and self-criticism begins.",
    "🎭 Adolescent Art (13-17 years old)": "Art becomes a tool for emotion, self-expression, and identity."
}

stages_info_copy = {
    "🖍️ The Scribbling Stage (2-4 years old)": {
        "desc": "Random lines and shapes – early motor development and expression. Toddlers, first use tools without an awareness that their actions produce marks. After continued exposure to materials, children produce bang dots, initial marks generated by hitting some tool against a surface.",
        "img": "assets/images/stage 1.jpg"
    },
    "🌈 The Preschematic Stage (4-7 years old)": {
        "desc": "Artwork in the preschematic stage is indicative of a child's proclivity to draw representationally. Images begin to resemble symbols, but these may only be understood by the child. Drawings created during this stage are often about elements of nature and fill the entire paper.",
        "img": "assets/images/stage 2.jpg"
    },
    "🏠 The Schematic Stage (7-9 years old)": {
        "desc": "Artwork created during the schematic stage is used as a tool for visual communication. Young artists develop specific schemas to portray objects. Children still tend to be more interested in the process of making art rather than the final product at this stage. A key characteristic and the benchmark at this level is the use of a baseline (either visual or assumed) or simply a more organized space. The child at this stage may also begin to show depth in their drawings. Additionally, the colors used are based on what the object actually looks like rather than having been arbitrarily chosen.",
        "img": "assets/images/stage 3.jpg"
    },
    "👫 The Gang Age (9-11 years old)": {
        "desc": "Peer influence and better spatial understanding. Art of the gang age stage marks the transition between art as purely symbolic to art as a creative outlet. Children at this stage will focus on developing an expertise in art and may often get frustrated throughout the process. Artists may begin to depict their subjects from multiple viewpoints and often multiple baselines are shown. Color is true to life in drawings from this stage, but elements of fantasy and illusion may be included in the form of world-making",
        "img": "assets/images/stage 4.jpg"
    },
    "🧠 The Stage of Reasoning (11-13 years old)": {
        "desc": "Realism increases, and self-criticism begins. Children begin to think abstractly around this age. Coordination and physical growth often fall out of alignment at this time, hindering the artist's ability to create what he believes he should be capable of. Additionally, children at this age begin to favor same-sex friendships rather than those of opposing sexes, often relating to issues of self-esteem",
        "img": "assets/images/stage 5.jpg"
    },
    "🎭 Adolescent Art (13-17 years old)": {
        "desc": "Art becomes a tool for emotion, self-expression, and identity. Throughout this stage of development, young artists begin to make art with an adult perspective. Although it is possible for all young artists to continue to this point, one must want to improve their artistic abilities. Through interpreting the world with a creative process, adolescents begin to approach their work as a mature artist would. The subjects of artwork at this stage vary depending on the interest of the artist and may range from extremely realistic to abstract. Artists in this stage tend to be motivated by social issues, emotions, or improving their own techniques, allowing for individualistic styles to emerge",
        "img": "assets/images/stage 6.jpg"
    },
}


stage_insights = {
    "The Scribbling Stage": "Your child's drawing shows early motor expressions and spontaneous exploration.",
    "The Preschematic Stage": "There's early use of symbolic representation, often colorful and centered.",
    "The Schematic Stage": "Your child is beginning to organize ideas using structured symbols like houses and people.",
    "The Gang Age": "Your child's art reflects social awareness and improved spatial relationships.",
    "The Stage of Reasoning": "They’re aiming for realism and logical placement of figures.",
    "Adolescent Art": "Emotional depth and personal meaning are becoming more evident in their drawings."
}

development_tips = {
    "The Scribbling Stage": [
        "Encourage free movement with large paper and crayons.",
        "Avoid asking 'What is it?' – focus on fun!"
    ],
    "The Preschematic Stage": [
        "Introduce basic shapes like circles and squares.",
        "Let them describe their drawings in their own words."
    ],
    "The Schematic Stage": [
        "Give them themes like 'My Family' or 'A Day at School'.",
        "Provide various drawing materials (markers, chalk, etc.)."
    ],
    "The Gang Age": [
        "Introduce group art projects to support social interaction.",
        "Give feedback focused on story and detail, not realism."
    ],
    "The Stage of Reasoning": [
        "Encourage them to draw from real life and observe proportions.",
        "Respect when they become self-critical — be positive."
    ],
    "Adolescent Art": [
        "Let them explore emotions and complex topics visually.",
        "Consider introducing digital art or advanced techniques."
    ]
}

recommended_activities = {
    "The Scribbling Stage": ["Finger painting", "Large brush strokes", "Music + drawing sessions"],
    "The Preschematic Stage": ["Coloring books", "Drawing animals", "Shape collages"],
    "The Schematic Stage": ["Draw a map", "Comic strips", "Daily sketching"],
    "The Gang Age": ["Art club participation", "Design your dream room", "Collaborative murals"],
    "The Stage of Reasoning": ["Portrait practice", "Still life drawing", "Animation basics"],
    "Adolescent Art": ["Digital illustration", "Emotive abstract art", "Art journaling"]
}
